### ISSUE TITLE
请教一下大佬，不是SO是elf二进制如何dump？

### ISSUE THREAD

**Issue by etjson** [maiyao1988/elf-dump-fix#5]
如题，对于某些root程序，他们的app并不是调用的so，而是直接另外cpp编译的二进制文件，直接通过root方式执行它，这种文件被压缩加壳，如何dump出来？无解么？

**Comment by maiyao1988** [comment]
你意思是直接命令行执行?这种程序执行的时候直接注入一个so dump出来

**Comment by etjson** [comment]
> 你意思是直接命令行执行?这种程序执行的时候直接注入一个so dump出来

具体是怎么操作？比如用什么工具注入啥的，这个二进制文件是通过root命令直接运行的，脱离了app本身，frida或者xp框架hook不到，直接通过pid来注入的话又不知道咋弄。

[demo.zip](https://github.com/maiyao1988/elf-dump-fix/files/7783938/demo.zip)

就是这种文件，大佬可以用IDA打开看一下，是加了壳了，然后又不是so，直接是cpp编译的二进制文件，必须root权限运行，可以strace调试。

**Comment by maiyao1988** [comment]
> > 你意思是直接命令行执行?这种程序执行的时候直接注入一个so dump出来
> 
> 具体是怎么操作？比如用什么工具注入啥的，这个二进制文件是通过root命令直接运行的，脱离了app本身，frida或者xp框架hook不到，直接通过pid来注入的话又不知道咋弄。
> 
> [demo.zip](https://github.com/maiyao1988/elf-dump-fix/files/7783938/demo.zip)
> 
> 就是这种文件，大佬可以用IDA打开看一下，是加了壳了，然后又不是so，直接是cpp编译的二进制文件，必须root权限运行，可以strace调试。

先注入，linux命令行注入使用环境变量LD_PRELOAD,参考
https://www.cnblogs.com/sandeepin/p/ld-preload-inject.html

注入的so写个init函数，在init 函数做hook，然后hook解壳之后会执行的函数 在里面把可执行文件dump出来

**Comment by etjson** [comment]
> > > 你意思是直接命令行执行?这种程序执行的时候直接注入一个so dump出来
> > 
> > 
> > 具体是怎么操作？比如用什么工具注入啥的，这个二进制文件是通过root命令直接运行的，脱离了app本身，frida或者xp框架hook不到，直接通过pid来注入的话又不知道咋弄。
> > [demo.zip](https://github.com/maiyao1988/elf-dump-fix/files/7783938/demo.zip)
> > 就是这种文件，大佬可以用IDA打开看一下，是加了壳了，然后又不是so，直接是cpp编译的二进制文件，必须root权限运行，可以strace调试。
> 
> 先注入，linux命令行注入使用环境变量LD_PRELOAD,参考 https://www.cnblogs.com/sandeepin/p/ld-preload-inject.html
> 
> 注入的so写个init函数，在init 函数做hook，然后hook解壳之后会执行的函数 在里面把可执行文件dump出来

没搞定，还是因为不懂C，大佬有没有什么现成可以用的dump工具？

**Comment by etjson** [comment]
@maiyao1988 
折腾几天了，没折腾出来。
