### ISSUE TITLE
error header is not .ELF!!!

### ISSUE THREAD

**Issue by liugang1014** [maiyao1988/elf-dump-fix#6]
我在dump一个app，其中一个so是加固的，dump后fix报错，能帮忙看下么？想还原脱壳后的so用于自己加载：
05056000-050da000 r--p 00056000 08:12 524811     /data/app/com.zhpphls.hema-2/lib/arm/libpp_hls.so
050da000-050db000 r--p 000d9000 08:12 524811     /data/app/com.zhpphls.hema-2/lib/arm/libpp_hls.so
050db000-051be000 rw-p 000da000 08:12 524811     /data/app/com.zhpphls.hema-2/lib/arm/libpp_hls.so
051be000-05375000 r--p 00000000 00:00 0

aosp:/data/local/tmp # ./dump 3082 0x04f23000 0x05375000 outfix.so 0 1
./dump 3082 0x04f23000 0x05375000 outfix.so 0 1
try dump 3082 from 0000000004f23000 to 0000000005375000
try to read /proc/3082/mem fp:3, off=0000000004f23000, sz=4530176
read return 4530176
4530176 writed
try fix outfix.so.tmp
error header is not .ELF!!!
end fix outfix.so.tmp output to outfix.so
aosp:/data/local/tmp #

**Comment by maiyao1988** [comment]
你的dump的首地址有问题吧，05056000才是那个so的首地址

**Comment by liugang1014** [comment]
> 

额 手误，解决了，十分感谢！我再测试下能否正常加载调用

**Comment by liugang1014** [comment]
尝试加载修复后的so，报 invalid shdr offset/size: 4530318/640，不是特别了解这块，再请教下

java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/~~Mdwc0w-pUFOAebJ71AFSTA==
                            vKOfA==/lib/arm/libpp_hls.so" has invalid shdr offset/size: 4530318/640
                         E      at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
                         E      at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
                         E      at java.lang.System.loadLibrary(System.java:1664)
<img width="669" alt="image" src="https://user-images.githubusercontent.com/5100512/169030505-1d915057-a366-46b8-86a8-b08695e0b11f.png">

**Comment by maiyao1988** [comment]
dump下来的so只能保证能ida分析，并不保证能加载

**Comment by liugang1014** [comment]
> dump下来的so只能保证能ida分析，并不保证能加载

哦了解了，有些什么建议么，最终还是想在手机里面调用，继续修补so？

**Comment by maiyao1988** [comment]
你想调用直接拿包里加壳的so去调用就行了。
